<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\PANiXiDA.Core.Application\PANiXiDA.Core.Application.csproj" />
        <ProjectReference Include="../../src/PANiXiDA.Core.Application.Generators/PANiXiDA.Core.Application.Generators.csproj"
                          OutputItemType="Analyzer" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
        <Using Include="Shouldly" />
    </ItemGroup>
</Project>
